
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    always_use_package_imports: error
    always_declare_return_types: error
    always_require_non_null_named_parameters: error
    avoid_empty_else: error
    avoid_final_parameters: error
    avoid_dynamic_calls: error
    avoid_print: error
    avoid_relative_lib_imports: error
    avoid_types_as_parameter_names: error
    avoid_unused_constructor_parameters: error
    avoid_web_libraries_in_flutter: error
    await_only_futures: error
    camel_case_extensions: error
    camel_case_types: error
    empty_catches: error
    empty_statements: error
    file_names: error
    library_names: error
    no_duplicate_case_values: error
    unawaited_futures: error
    unnecessary_new: error
    void_checks: error
    invalid_assignment: info
    avoid_single_cascade_in_expression_statements: error
    argument_type_not_assignable: ignore
    eol_at_end_of_file: ignore
    sort_child_properties_last: ignore
    require_trailing_commas: ignore 
    prefer_is_empty: ignore
    unnecessary_parenthesis: ignore
    
linter:
  rules:
    always_use_package_imports: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: false
    always_require_non_null_named_parameters: true
    avoid_empty_else: true
    avoid_final_parameters: true
    avoid_dynamic_calls: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_types_as_parameter_names: true
    avoid_unused_constructor_parameters: true
    avoid_web_libraries_in_flutter: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    cast_nullable_to_non_nullable: false
    empty_catches: true
    empty_statements: true
    file_names: true
    library_names: true
    no_duplicate_case_values: true
    curly_braces_in_flow_control_structures: false
    unawaited_futures: true
    unnecessary_new: true
    void_checks: true
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors: false
    avoid_single_cascade_in_expression_statements: true
